name: Desafio

on: push
jobs:
 build:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    services:
      mysql:
        image: mysql
        env:
          MYSQL_USERNAME: sail
          MYSQL_PASSWORD: password
          MYSQL_DB: desafio_api
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Prepare Laravel App
        run: cp .env.desafio .env

      - name: Composer Install
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Generate Key
        run: php artisan key:generate

      - name: Migrations
        run: php artisan migrate

      - name: Install NPM Packages
        run: |
          npm install
          npm run production

      - name: Run tests
        run: php artisan test




